// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKS_MbeZVXRU1BzlzYXFECZuavyRogsiw',
    appId: '1:701123620337:web:a3d4ec8157b92e66062850',
    messagingSenderId: '701123620337',
    projectId: 'aifitnes',
    authDomain: 'aifitnes.firebaseapp.com',
    storageBucket: 'aifitnes.firebasestorage.app',
    measurementId: 'G-HN1YJ43JPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdc4QjTYVhnicrMLq-WVyp7rBD42soj8I',
    appId: '1:701123620337:android:e8aa2c55db107c01062850',
    messagingSenderId: '701123620337',
    projectId: 'aifitnes',
    storageBucket: 'aifitnes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD66NxQAjr_8XgfiZ66N7e7w611KDqgFN4',
    appId: '1:701123620337:ios:512aff1e56c27958062850',
    messagingSenderId: '701123620337',
    projectId: 'aifitnes',
    storageBucket: 'aifitnes.firebasestorage.app',
    iosBundleId: 'com.startap.startap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD66NxQAjr_8XgfiZ66N7e7w611KDqgFN4',
    appId: '1:701123620337:ios:512aff1e56c27958062850',
    messagingSenderId: '701123620337',
    projectId: 'aifitnes',
    storageBucket: 'aifitnes.firebasestorage.app',
    iosBundleId: 'com.startap.startap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKS_MbeZVXRU1BzlzYXFECZuavyRogsiw',
    appId: '1:701123620337:web:5a614afd8849eac1062850',
    messagingSenderId: '701123620337',
    projectId: 'aifitnes',
    authDomain: 'aifitnes.firebaseapp.com',
    storageBucket: 'aifitnes.firebasestorage.app',
    measurementId: 'G-196QNV9RWN',
  );
}
